---
sudo: false

language: python

python: 3.8

services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-ntpdate triviadata.ntpdate
  - cd triviadata.ntpdate

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
