---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
      when: ansible_distribution == 'Ubuntu'

  roles:
    - role: triviadata.ntpdate
